import { improvedTimeFormat } from './timeFormat.mjs';
import { getLeadingBid } from './findLeadingBid.mjs';
function createHTMLSpecific(object, section) {
  let { description, endsAt, media, title, bids } = object;
  let specificCon = document.createElement('div');
  let divEndAndBids = document.createElement('div');
  let h1 = document.createElement('h1');
  let desc = document.createElement('p');
  let endDate = document.createElement('p');
  let newEndsAt = improvedTimeFormat(endsAt);
  let bidHistoryCon = document.createElement('div');
  let bidHistory = document.createElement('p');
  let imgCon = document.createElement('div');
  let img = document.createElement('img');
  let currentBid = document.createElement('p');
  let totalBid = document.createElement('p');
  let bidCta = document.createElement('button');
  img.src = media;
  bidHistory.innerText = 'Bid History';
  currentBid.innerText = getLeadingBid(bids);
  h1.innerText = title;
  bidCta.innerText = 'Bid now';
  desc.innerText = description;
  endDate.innerText = `Ends at: ${newEndsAt}`;
  divEndAndBids.append(currentBid);
  divEndAndBids.append(totalBid);
  divEndAndBids.append(endDate);
  bidHistoryCon.append(bidHistory);
  totalBid.innerText = `Total bids: ${bids.length}`;
  desc.classList.add('text-white');
  section.classList.add('text-white');
  imgCon.append(img);
  img.classList.add('img-fluid');
  imgCon.classList.add('imgSpecific');
  h1.classList.add('my-3');
  endDate.classList.add('text-golden');
  endDate.classList.add('text-center');
  desc.classList.add('p-1');
  desc.classList.add('text-center');
  divEndAndBids.classList.add('w-100');
  section.classList.add('bg-black');
  specificCon.append(h1);
  specificCon.append(imgCon);
  specificCon.append(desc);
  specificCon.append(divEndAndBids);
  specificCon.append(bidCta);
  specificCon.append(bidHistoryCon);

  section.append(specificCon);
}
export { createHTMLSpecific };
