const BASE_URL = 'https://api.noroff.dev/api/v1';
const REGISTER_ENDPOINT = '/auction/auth/register';
const LOGIN_ENDPOINT = '/auction/auth/login';
const PROFILE_ENPOINT = '/auction/profiles/';
const AUCTION_ENDPOINTS = '/auction/listings';
const REGISTER_URL = BASE_URL + REGISTER_ENDPOINT;
const LOGIN_URL = BASE_URL + LOGIN_ENDPOINT;
const PROFILE_URL = BASE_URL + PROFILE_ENPOINT;
const AUCTION_URL = BASE_URL + AUCTION_ENDPOINTS;
export { REGISTER_URL, LOGIN_URL, PROFILE_URL, AUCTION_URL };
